# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Allergen.create(category:"Dodecyl gallate", substances:"4-10-00-02006; BRN 2701981; Benzoic acid, 3,4,5-trihydroxy-, dodecyl ester; CCRIS 5568; Dodecyl 3,4,5-trihydroxybenzoate; Dodecyl gallate; Dodecylester kyseliny gallove; Dodecylester kyseliny gallove; EINECS 214-620-6; Gallic acid, dodecyl ester; Gallic acid, lauryl ester; Lauryl 3,4,5-trihydroxybenzoate; Lauryl gallate; NSC 133463; Nipagallin LA; Progallin LA
")
Allergen.create(category:" Benzoyl Peroxide", substances:"Abcat 40; Acetoxyl; Acne-Aid Cream; Acnegel; Akneroxid 5; Akneroxide L; Aksil 5; Asidopan; Aztec BPO; B 75W; BPO; BZF-60; Benbel C; Benox 50; Benoxyl; Benoxyl (5&10) Lotion; Benzac; Benzac W; Benzagel; Benzagel 10; Benzaknen; Benzashave; Benzoic acid, peroxide; Benzol peroxide; Benzoperoxide; Benzoyl peroxide; Benzoyl superoxide; Benzoylperoxid; Benzoylperoxid; Benzoylperoxyde; Benzoylperoxyde; Brevoxyl; CCRIS 630; Cadat BPO; Cadox 40E; Cadox B; Cadox B 40E; Cadox B 50P; Cadox B 70W; Cadox B-CH 50; Cadox BS; Chaloxyd BP 50FT; Clear By Design; Clearasil Antibacterial Acne Lotion; Clearasil BP Acne Treatment Cream; Debroxide; Desanden; Desquam E; Desquam X; Dibenzoyl peroxide; Dibenzoylperoxid; Dibenzoylperoxid; Dibenzoylperoxyde; Dibenzoylperoxyde; Diphenylglyoxal peroxide; Dry and Clear; Duresthin 5; EINECS 202-327-6; Eloxyl; Epi Clear Antiseptic Lotion; Epi-Clear; Fostex; G 20; Garox; HSDB 372; Incidol; Loroxide; Lucidol; Lucidol (peroxide); Lucidol 50P; Lucidol B 50; Lucidol G 20; Lucidol KL 50; Lucidol-70; Luperco AA; Luperco AST; Luperox FL; Mytolac; NSC 671; Nayper B and BO; Nayper bo; Norox bzp-250; Norox bzp-C-35; Novadelox; Oxy-10; Oxy-10 Cover; Oxy-5; Oxylite; PanOxyl; Perossido di benzoile; Perossido di benzoile; Peroxide, dibenzoyl; Peroxyde de benzoyle; Peroxyde de benzoyle; Persa-Gel; Persadox; Quinolor compound; Resdan Akne; Stri-dex B.P.; Superox 744; Theraderm; Topex; Vanoxide; Xerac; epi-Clear
")
Allergen.create(category:"Tosylamide/Formaldehyde Resin", substances:"4-Toluenesulfonamide-formaldehyde resin; Benzenesulfonamide, 4-methyl-, polymer with formaldehyde; Tosylamide/formaldehyde resin; Santolite MS; Santolite MHP
")
Allergen.create(category:"1,3,5-tris(2-hydroxyethyl)-hexahydrotriazine ", substances:"1,3,5-Tris(2-hydroxyethyl)hexahydro- 1,3,5-triazine; 1,3,5-Tris(2-hydroxyethyl)hexahydro-striazine; 4-26-00-00010; Actane; BRN 0124982; Busan 1060; CCRIS 6246; Caswell No. 481C; EINECS 225-208-0; EPA Pesticide Chemical Code 083301; ETA 75; Grotan; Grotan B; Grotan BK; Grotan HD; Hexahydro-1,3,5-triazine-1,3,5-triethanol; Hexahydro-1,3,5-tris(2-hydroxyethyl)-striazine; Hexahydro-1,3,5-tris(hydroxyethyl)triazine; KM 200 (alcohol); Kalpur TE; NSC 516387; Onyxide 200; Ottaform 204; Rancidity control agent; Roksol T 1-7
")
Allergen.create(category:"Urea formaldehyde resin ", substances:"Formaldehyde, urea polymer; Gabrite; HSDB 7203; Hygromull; KM 2 (Polymer); Karbamol; Karbamol B/M; Kauresin K244; Kaurit 285 FL; Kaurit 420; PR 703-78; Pianizol; Piatherm; Piatherm D; Plastopal BT; Plyamine HD 1129A; Plyamine P 364BL; Poly(methi(bis(hydroxymethyl))ureylene) amer; Polynoxylin; Ponoxylan; Resamin 155F; Resamin HW 505; Resina X; S-Resin AER 20; Uformite 700; Uformite F 240N; Uloid 100; Uloid 22; Urea formaldehyde polymer; Urea formaldehyde resin; Urea, paraformaldehyde polymer; Urea, polymer with 1-butanol and formaldehyde; Urea, polymer with formaldehyde
")
Allergen.create(category:"Formaldehyde", substances:"Formaldehyde; Formalin; Formic aldehyde; Methaldehyde; Methyl aldehyde; Methylene oxide; Methanal; Oxymethylene; Quaternium-15; Diazolidinyl urea ; Germall II; DMDM hydantoin ; Glydant; Imidazolidinyl urea ; Germall; 2-bromo-2-nitropropane-1,3-diol ; Bronopol; Tris nitromethane ; Tris Nitro
")
Allergen.create(category:"Hexamethylenetetramine", substances:"1,3,5,7-Tetraazaadamantane; 1,3,5,7-Tetraazatricyclo(3.3.1.1(3,7))decane; 1,3,5,7-Tetraazatricyclo(3.3.1.1(sup 3,7))decane; 1,3,5,7-Tetraazatricyclo(3.3.1.1(sup 37))decane; AI3-09611; Aceto HMT; Aminoform; Aminoformaldehyde; Ammoform; Ammonioformaldehyde; Antihydral; CCRIS 2297; Caswell No. 482; Cystamin; Cystogen; Duirexol; EINECS 202-905-8; EPA Pesticide Chemical Code 45501; Ekagom H; Esametilentetramina; Esametilentetramina; Formamine; Formin; Formin (heterocycle); HMT; HSDB 563; Herax UTS; Heterin; Hexa (vulcanization accelerator); Hexa-Flo-Pulver; Hexaform; Hexaloids; Hexamethylenamine; Hexamethyleneamine; Hexamethylenetetraamine; Hexamethylenetetramine; Hexamethylenetetraminum; Hexamethylentetramin; Hexamethylentetramin; Hexamethylentetramine; Hexamethylentetraminum; Hexamine; Hexamine (heterocycle); Hexaminum; Hexasan; Hexasan (VAN); Hexilmethylenamine; Metenamina; Metenamina; Methenamin; Methenamine; Methenaminum; Methenaminum; Metramine; NSC 26346; NSC 403347; Nocceler H; Preparation AF; Resotropin; S 4 (heterocycle); Sanceler H; Uramin; Uratrine; Uritone; Urodeine; Urotropin; Urotropine; Vulkacit H 30; Xametrin
")
Allergen.create(category:"Dimethylaminopropylamine (DMAPA)", substances:"1,3-Propanediamine, N,N-dimethyl-; 1-(Dimethylamino)-3-aminopropane; 1-Amino-3-dimethylaminopropane; 3-(Dimethylamino)-1-propanamine; 3-(Dimethylamino)-1-propylamine; 3-(Dimethylamino)propylamine; 3-Amino-1-(dimethylamino)propane; 4-04-00-01259; AI3-25441; BRN 0605293; CCRIS 4799; EINECS 203-680-9; HSDB 5391; N,N-Dimethyl-1,3-diaminopropane; N,N-Dimethyl-1,3-propanediamine; N,N-Dimethyl-1,3-propylenediamine; N,N-Dimethyl-N-(3-aminopropyl)amine; N,N-Dimethylpropylenediamine; N,N-Dimethyltrimethylenediamine; N-Dimethyltrimethylenediamine; NSC 1067; Propylamine, 3-(N,N-dimethylamino)-; gamma-(Dimethylamino)propylamin
")
Allergen.create(category:"4-(4-hydroxy-4-methyl pentyl)-3-cyclohexene-1- carboxaldehyde (Lyral)", substances:"4-(4-Hydroxy-4-methylpentyl)-3-cyclohexene-1-carboxaldehyde; BRN 2046455; EINECS 250-863-4; Lyral
")
Allergen.create(category:"Fragrance Mix II", substances:"2H-1-Benzopyran-2-one; Coumarin; Tonka bean camphor; 1,2-Benzopyrone; 2-Oxo-1,2-benzopyran; 2-Propenoic acid, 3-(2-hydroxyphenyl)-, delta-lactone; 2-Propenoic acid, 3-(2-hydroxyphenyl)-delta-lactone; 2H-1-Benzopyran, 2-oxo-; 2H-1-Benzopyran-2-one; 2H-Benzo(b)pyran-2-one; 3-(2-Hydroxyphenyl)-2-propenoic delta-lactone; 5,6-Benzo-alpha-pyrone; 5-17-10-00143 (Beilstein Handbook Reference); AI3-00753; Alpha-hexylcinnamic aldehyde; BRN 0383644; Benzo-alpha-pyrone; CCRIS 181; Caswell No. 259C; Cinnamic acid, o-hydroxy-, delta-lactone; Citral ; Coumarin; Coumarinic anhydride; Coumarinic lactone; Cumarin; EINECS 202-086-7; EPA Pesticide Chemical Code 127301; Farnesol ; Lyral ; Rattex; Tonka bean camphor; cis-o-Coumaric acid anhydride; cis-o-Coumarinic acid lactone; o-Coumaric acid lactone; o-Hydroxycinnamic acid lactone; o-Hydroxycinnamic lactone; 4-(4-Hydroxy-4-methylpentyl)-3-cyclohexene-1-carboxaldehyde; BRN 2046455; EINECS 250-863-4; 3-Cyclohexene-1-carboxaldehyde, 4-(4-hydroxy-4-methylpentyl)-; 4-(4-Hydroxy-4-methylpentyl)cyclohex-3-enecarbaldehyde; 3-Cyclohexene-1-carboxaldehyde, 4-(4-hydroxy-4-methylpentyl)-; 2,6-Dimethyl-2-octen-8-ol; 3,7-Dimethyl-6-octen-1-ol; 4-01-00-02188; AI3-25080; BRN 1721507; CCRIS 7452; Cephrol; Citronellol (ex. Java citronella oil); Citronellol; EINECS 203-375-0; Elenol; FEMA No. 2309; NSC 8779; Rhodinol; Rodinol; 2,6,10-Dodecatrien-1-ol, 3,7,11-trimethyl-; 3,7,11-Trimethyl-2,6,10-dodecatrienol; 3,7,11-Trimethyl-2,6,10-dodecatrien-1-ol; Trimethyl dodecatrienol
")
Allergen.create(category:"4,4'-diaminodiphenyl methane", substances:"4,4'-Diaminodiphenylmethan; 4,4'-Diaminodiphenylmethan; 4,4'-Diaminodiphenylmethane; 4,4'-Dimethylenediamine; 4,4'-Diphenylmethanediamine; 4,4'-Methylenebis(benzeneamine); 4,4'-Methylenebisaniline; 4,4'-Methylenedianiline; 4-(4-Aminobenzyl)aniline; 4-13-00-00390; AI3-02615; Ancamine TL; Aniline, 4,4'-methylenedi-; Araldite hardener 972; Avaldite HT 972; BRN 0474706; Benzenamine, 4,4'-methylenebis-; Bis(4-aminophenyl)methane; Bis(p-aminophenyl)methane; Bis-p-aminofenylmethan; Bis-p-aminofenylmethan; CCRIS 1010; Curithane; Dadpm; Di-(4-aminophenyl)methane; Diaminodiphenylmethane; Dianilinemethane; Dianilinomethane; EINECS 202-974-4; Epicure DDM; Epikure DDM; HSDB 2541; HT 972; Jeffamine AP-20; MDA; Methylenebis(aniline); Methylenedianiline; Methylenedianiline (VAN); NCI-C54604; NSC 4709; Sumicure M; Tonox; p,p'-Diaminodifenylmethan; p,p'-Diaminodifenylmethan; p,p'-Diaminodiphenylmethane; p,p'-Methylenedianiline; p-Toluidine, alpha-(p-aminophenyl)- 
")
Allergen.create(category:"Disperse Orange-3", substances:"EINECS 211-984-8; Orange 3
")
Allergen.create(category:"P-phenylenediamine base", substances:"1,4-Benzenediamine, 2-methyl-; 2,5-Diaminotoluene; 2-Methyl-1,4-benzenediamine; 2-Methyl-p-phenylenediamine; 2-Methyl-para-phenylenediamine; 4-13-00-00246; 4-Amino-2-methylaniline; BRN 0774521; C.I. 76042; CCRIS 7693; CI 76042; EINECS 202-442-1; HSDB 6251; Toluene-2,5-diamine; Toluylene-2,5-diamine; p,m-Tolylenediamine; p-Toluenediamine; p-Toluylendiamine; para-Toluenediamine; para-Toluylenediamine; para-Tolylenediamine
")
